version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for SQS Handler Lambda..."
      - cd sqsEventHandler  # ⬅️ Assuming your code is inside the `sqshandler/` folder
      - npm install
  build:
    commands:
      - echo "Zipping SQS Handler Lambda..."
      - zip -r sqs-handler.zip .
artifacts:
  files:
    - sqsEventHandler/sqs-handler.zip
  discard-paths: yes
