version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for Backend Lambda..."
      - cd nodejsbackend    # ⬅️ Go inside nodejsbackend first
      - npm install
  build:
    commands:
      - echo "Zipping Backend Lambda..."
      - cd nodejsbackend    # ⬅️ Stay inside while zipping too
      - zip -r backend-lambda.zip .
artifacts:
  files:
    - nodejsbackend/backend-lambda.zip
  discard-paths: yes
