version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for Backend Lambda..."
      - cd nodejsbackend
      - npm install
  build:
    commands:
      - echo "Zipping Backend Lambda..."
      - cd nodejsbackend
      - zip -r backend-lambda.zip .
artifacts:
  base-directory: nodejsbackend
  files:
    - backend-lambda.zip
  discard-paths: yes
