version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for CSV Processor Lambda..."
      - pip install boto3
  build:
    commands:
      - echo "Zipping CSV Processor Lambda..."
      - zip -r csv-processor.zip .
artifacts:
  files:
    - csv-processor.zip
  discard-paths: yes
